import Head from "next/head";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative isolate flex min-h-screen flex-col bg-gradient-to-tr from-[#1f2937] to-[#1f1e20] px-6 lg:px-8">
        <div
          className="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80"
          aria-hidden="true"
        >
          <div
            className="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#a8c4a6] to-[#1f2937] opacity-30 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]"
            style={{
              clipPath:
                "polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)",
            }}
          />
        </div>
        <Header />
        <div className="mx-auto mt-16 max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="flex flex-1 items-center space-x-12">
            <div>
              <h1 className="text-4xl font-bold text-white sm:text-6xl lg:text-7xl">
                Take unorganized notes with
                <div className="relative inline-flex">
                  <h1 className="relative inline-block bg-gradient-to-r from-[#906fcd] via-[#bbb0cf] to-indigo-400 bg-clip-text pb-3 text-4xl font-bold text-transparent sm:text-6xl lg:text-7xl">
                    Company
                  </h1>
                </div>
              </h1>

              <p className="mt-6 text-base text-white sm:text-xl">
                Amet minim mollit non deserunt ullamco est sit aliqua dolor do
                amet sint. Velit officia consequat duis enim velit mollit.
                Exercitation veniam consequat.
              </p>

              <div className="mt-10 sm:flex sm:items-center sm:space-x-8">
                <Link
                  href="#"
                  title=""
                  className="inline-flex items-center justify-center rounded-full bg-[#906fcd] px-10 py-4 text-base font-semibold text-white transition-all duration-200 hover:bg-[#8459d2] "
                  role="button"
                >
                  Get Started
                </Link>
              </div>
            </div>

            <div className="flex w-full">
              <Image
                width={512}
                height={512}
                className="w-full"
                src="https://cdn.rareblocks.xyz/collection/celebration/images/hero/2/hero-img.png"
                alt=""
              />
            </div>
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
}
